### ISSUE TITLE
NAME table suggestions

### ISSUE THREAD

**Issue by davelab6** [erinmclaughlin/Yantramanav#1]
- [x] In https://github.com/erinmclaughlin/Yantramanav/blob/master/UFO/Black/Yantramanav-Black.ufo/fontinfo.plist#L10 change this to `Copyright (c) 2014, Erin McLaughlin (hello@erinmclaughlin.com). Copyright (c) 2010, Google Inc. All Rights Reserved.`
- [x] In https://github.com/erinmclaughlin/Yantramanav/blob/master/UFO/Black/Yantramanav-Black.ufo/fontinfo.plist#L108-L109 change `GOOG` to something else, perhaps `ERIN` ? :) 
- [x] In https://github.com/erinmclaughlin/Yantramanav/blob/master/UFO/Black/Yantramanav-Black.ufo/fontinfo.plist#L158-L163 the styleName should be Regular and 
- [x] In https://github.com/erinmclaughlin/Yantramanav/blob/master/UFO/Yantramanav-tables.fea#L49-L82 you'll want to set these correctly too, I believe, although I don't have enough personal experience with FDK to know for sure
- [x] In https://github.com/erinmclaughlin/Yantramanav/blob/master/UFO/Black/Yantramanav-Black.ufo/fontinfo.plist#L166-L167 you have a 2048 UPM; I'm curious why you picked this - was it inherited from Roboto?

**Comment by erinmclaughlin** [comment]
Hi Dave! Yep, 2048 was from Roboto and also Lohit, from which I originally started both of my projects. Sorry for the delay, I'll fix these tomorrow.
